image: alpine:latest

variables:
    DOCKER_DRIVER: overlay2
    ROLLOUT_RESOURCE_TYPE: deployment

stages:
    - build
    - push
    - deploy
    - cleanup

include:
  - template: Jobs/Build.gitlab-ci.yml # https://gitlab.com/gitlab-org/gitlab-foss/blob/master/lib/gitlab/ci/templates/Jobs/Build.gitlab-ci.yml
  - template: Jobs/Deploy.gitlab-ci.yml # https://gitlab.com/gitlab-org/gitlab-foss/blob/master/lib/gitlab/ci/templates/Jobs/Deploy.gitlab-ci.yml


