variables:
    DOCKER_DRIVER: overlay2

stages:
    - build
    - push
    - deploy

build:
    stage: build
    image: docker:latest
    services: 
        - name: docker:stable-dind
        - command: ["--insecure-registry=dockerhub.com"]
    script:
    - docker build -t node-app:$CI_PIPELINE_ID .
    artifacts:
        paths:
            - Dockerfile
    allow_failure: false

push:
    stage: push
    image: docker:latest
    services:
        - docker.dind
    script:
        - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASS"
        - docker tag node-app:$CI_PIPELINE_ID panjol/node-app:$CI_PIPELINE_ID
        - docker push panjol/node-app:$CI_PIPELINE_ID
    allow_failure: false

deploy:
    stage: deploy
    image: google/cloud-sdk
    script:
        - gcloud auth activate-service-account --key-file $GCP_
        - kubectl apply -f service.yml
    dependencies:
        - push
    when: on_success