stages:
    - build
    - deploy

build:
    stage: build
    image: docker:latest
    dependencies:
        - build-app
    services:
        - docker:dind
    before_script:
        - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASS"
    script:
        - docker build -t node:$CI_PIPELINE_ID .
        - docker tag node:$CI_PIPELINE_ID panjol/node:$CI_PIPELINE_ID
        - docker push panjol/node:$CI_PIPELINE_ID
    artifacts:
        paths:
            - Dockerfile
    allow_failure: false

deploy:
    stage: deploy
    image: google/cloud-sdk
    script:
        - gcloud auth activate-service-account --key-file $GCP_
        - kubectl apply -f service.yml
    dependencies:
        - push
    when: on_success