stages:
    - build
    - deploy
variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    DOCKER_TLS_CERTDIR: "/certs"
build:
    stage: build
    image: docker:latest
    services:
        - docker:dind
    before_script:
        - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASS"
    script:
        - docker build -t node:$CI_PIPELINE_ID .
        - docker tag node:$CI_PIPELINE_ID panjol/node:$CI_PIPELINE_ID
        - docker push panjol/node:$CI_PIPELINE_ID
    artifacts:
        paths:
            - /tmp/build/*
    allow_failure: false

deploy:
    stage: deploy
    image: google/cloud-sdk:alpine
    script:
        - export GCP_SERVICE_ACCOUNT_KEY > key.json
        - gcloud auth activate-service-account --key-file=key.json
        - gcloud config set project $GCP_PROJECT_ID
        - gcloud config set container/cluster GKE_CLUSTER
        - gcloud config set compute/zone asia-south1-b
        - gcloud container clusters get-credentials GKE_CLUSTER_NAME --zone asia-south1-b --project GCP_PROJECT_NAME
        - sed -i "s/<VERSION>/${CI_COMMIT_SHORT_SHA}/g" serivce.yaml
        - kubectl apply -f service.yaml

        ##akdnaknd
    dependencies:
        - build
#    environment:
 #       name: production
