image: alpine:latest
stages:
    - build
    - push
    - deploy

build:
    stage: build
    script:
    - docker build -t node:$CI_PIPELINE_ID .
    artifacts:
        paths:
            - Dockerfile
    allow_failure: false

push:
    stage: push
    script:
        - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASS"
        - docker tag node:$CI_PIPELINE_ID panjol/node:$CI_PIPELINE_ID
        - docker push panjol/node:$CI_PIPELINE_ID
    allow_failure: false

deploy:
    stage: deploy
    script:
        - kubectl apply -f service.yml
    dependencies:
        - push
    when: on_success