stages:
    - build
    - deploy
variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    DOCKER_TLS_CERTDIR: "/certs"
build:
    stage: build
    image: docker:latest
    services:
        - docker:dind
    before_script:
        - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASS"
    script:
        - docker build -t node:$CI_PIPELINE_ID .
        - docker tag node:$CI_PIPELINE_ID panjol/node:$CI_PIPELINE_ID
        - docker push panjol/node:$CI_PIPELINE_ID
    artifacts:
        paths:
            - Dockerfile
    allow_failure: false

deploy:
    stage: deploy
    image: google/cloud-sdk:alpine
    script:
      - apk add --update --no-cache curl
      - mkdir -p /kubeconfig
      - echo "$KUBECONFIG_CONTENTS" | base64 -d > $KUBECONFIG
      - kubectl config use-context $KUBE_CONTEXT
      - envsubst < service.yml | kubectl apply -f -
    dependencies:
        - build
    environment:
        - name: production
