stages:
    - build
    - deploy
variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    DOCKER_TLS_CERTDIR: "/certs"
build:
    stage: build
    image: docker:latest
    services:
        - docker:dind
    before_script:
        - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASS"
    script:
        - docker build -t node:$CI_PIPELINE_ID .
        - docker tag node:$CI_PIPELINE_ID panjol/node:$CI_PIPELINE_ID
        - docker push panjol/node:$CI_PIPELINE_ID
    artifacts:
        paths:
            - /tmp/build/*
    allow_failure: false

deploy:
    stage: deploy
    image: google/cloud-sdk:alpine
    script:
        - echo $SERVICE_ACCOUNT | base64 -d > ~/encoded_serviceaccount.json
        - gcloud auth activate-service-account --key-file ~/encoded_serviceaccount.json
        - gcloud config set project calm-vehicle-380009
        - gcloud config set compute/zone asia-southeast1-b
        - gcloud container clusters get-credentials node-cluster --region asia-southeast1 --project calm-vehicle-380009
        - kubectl apply -f service.yaml

        ##akdnaknd
    dependencies:
        - build
#    environment:
 #       name: production