name: Deploy to DigitalOcean Droplet

on:
  push:
    branches:
      - master

env:
  DIGITALOCEAN_DROPLET_IP: 159.65.138.146
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: your-dockerhub-username/node-app:latest

      - name: Install sshpass
        run: sudo apt-get -y install sshpass

      - name: Deploy to DigitalOcean Droplet
        run: |
          sshpass -p ${{ secrets.DROPLET_PASSWORD }} ssh -o StrictHostKeyChecking=no root@${{ env.DIGITALOCEAN_DROPLET_IP }} 'docker stop node-app && docker rm node-app || true'
          sshpass -p ${{ secrets.DROPLET_PASSWORD }} scp -o StrictHostKeyChecking=no -r . root@${{ env.DIGITALOCEAN_DROPLET_IP }}:/root/node-app
          sshpass -p ${{ secrets.DROPLET_PASSWORD }} ssh -o StrictHostKeyChecking=no root@${{ env.DIGITALOCEAN_DROPLET_IP }} 'cd /root/node-app && docker build -t your-dockerhub-username/node-app .'
          sshpass -p ${{ secrets.DROPLET_PASSWORD }} ssh -o StrictHostKeyChecking=no root@${{ env.DIGITALOCEAN_DROPLET_IP }} 'docker run -d -p 9005:9005 --name node-app your-dockerhub-username/node-app:latest'
