---
name: Push to ECR

on:
  push:
    branches: [ master ]  # Change this to your main branch name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-3  # Change this to your desired AWS region

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and tag Docker image
        run: |
          docker build -t node-app:latest .
          docker tag node-app:latest ${{ steps.login-ecr.outputs.registry }}/vanzoel:latest

      - name: Push Docker image to ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/vanzoel:latest

      - name: SSH into EC2 instance and deploy
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > ec2_private_key.pem
          chmod 400 ec2_private_key.pem
          ssh -i ec2_private_key.pem ubuntu@ec2-108-136-231-117.ap-southeast-3.compute.amazonaws.com << EOF
    
          docker stop my-container || true
          docker rm my-container || true

          docker pull ${{ steps.login-ecr.outputs.registry }}/vanzoel:latest
          docker run -d --name my-container -p 9005:9005 ${{ steps.login-ecr.outputs.registry }}/vanzoel:latest
          EOF
        shell: bash
